### ISSUE TITLE
Feature Request: Add the ability to load CABundle from cluster in AppBinding

### ISSUE THREAD

**Issue by arnarg** [kubevault/issues#59]
When you do not provide TLS and a CA Bundle and just let KubeVault generate self signed ones for you it's not possible to ship AppBinding at the same time without `clientConfig.insecureSkipTLSVerify`.

In the documentation that is discouraged, understandably, so you have to do the following steps:

1. Deploy Vault using a `VaultServer` config without specifying TLS and CA.
2. After KubeVault has generated the CA and TLS you have to get the CABundle from the cluster.
3. Copy that CABundle into the AppBinding.

This is a manual process and not possible with automatic workflow.

I propose that the operator should be able to get this information from the cluster by one of the following methods:

- In the source code it is mentioned that [the CABundle will be stored in the tls-secret](https://github.com/kubevault/operator/blob/0.2.0/pkg/controller/vault.go#L91-L95) which it [does not do](https://github.com/kubevault/operator/blob/0.2.0/pkg/controller/vault.go#L146-L156). Provided that it does that you could allow `clientConfig.caBundle` to start with `$` to signify that it should be loaded from a secret ([$ is not in Base64](https://en.wikipedia.org/wiki/Base64#Base64_table), so parsing should be as simple as checking if string begins with `$` without any risk of breaking the old way).
  Example:
  ```
  clientConfig:
    caBundle: $vault-vault-tls.ca.crt
  ```

- When the CA Bundle and TLS certificates are generated they are added to the `VaultServer` config under `.spec.tls.caBundle`. The AppBinding could get it from there somehow.
  Again, `$` could be used to signify which `VaultServer` to get it from.
  You could even target a `VaultServer` instead of a `Service` in the first place if it is possible for the operator to get the `Service` from that.

**Comment by arnarg** [comment]
Is there any interest in this?

**Comment by tamalsaha** [comment]
@arnarg, I am confused why are you manually creating the `AppBinding`. Vault server operator will create the AppBinding for you. https://github.com/kubevault/operator/blob/85ffd964e2e37d530848d9d58f994fb10c952c21/pkg/controller/appbinding.go#L16

The reason we don't add ca.crt into the TLS secret is because Kubernetes does not allow any key other than tls.crt and tls.key when secret type is set to `kubernetes.io/tls` . Here I saw that we did not set the secret type, but we should fix that. https://github.com/kubernetes/api/blob/334089439675d2a85c879ed262fc082e20fbcc3d/core/v1/types.go#L5108

Lastly, I suppose this is some sort of Gitops issue. We are interested in solving/helping here. Though the idea of using `$` does not sound exciting. AppBinding is supposed to be independent and decoupled from how Vault server is provisioned. So, if you can tell us bit more about your use-case, we can find a solution.

**Comment by arnarg** [comment]
> I am confused why are you manually creating the AppBinding. Vault server operator will create the AppBinding for you.
Oh I missed that part :P

Then I have no issue with this and I'll close the issue. Thanks.
